//este levanta el servidor de mongo y menciona enque ruta sera guardado la base de datos, en ello se deve crear una carpeta para la base de datos...
start cmd.exe /k "cd /d C:\Program Files\MongoDB\Server\7.0 && mongod.exe --dbpath C:\data"


start cmd.exe /k "cd /d C:\Users\xavil\proyecto nuevo\backend_redsocial && npm run start:watch"

//C:\Users\xavil\proyecto nuevo\backend_redsocial: esta es la de casa donde esta ubicado el proyecto...
//C:\Users\EQUIPO_GEN07\NUEVO PROYECTO REACT\context_api\backend_redsocial: estes de la ofc...